"""Named constants shared across services. No magic numbers at call sites."""

DEFAULT_RELEVANCE_SCORE_THRESHOLD = 0.70

DEFAULT_MORNING_RUN_HOUR = 7
DEFAULT_EVENING_RUN_HOUR = 19

MAX_COVER_LETTER_CHARS = 4000
MAX_JOB_DESCRIPTION_CHARS = 20000

HTTP_REQUEST_TIMEOUT_SECONDS = 30
